#------------------------------------------------------------------------------
# PCIe Video Capture Card - Pin Constraints
# Target Device: XC7K480TFFG1156-2
#
# Phase 1: Color Bar Generator Validation
# Reference: XC7K480T_MicroBlaze_Test
#------------------------------------------------------------------------------

#==============================================================================
# System Clock (Reference: XC7K480T_MicroBlaze_Test)
#==============================================================================

# 200MHz oscillator
set_property PACKAGE_PIN AA28 [get_ports sys_clk_200m]
set_property IOSTANDARD LVCMOS18 [get_ports sys_clk_200m]

# System reset button
set_property PACKAGE_PIN R28 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports sys_rst_n]
set_property PULLUP true [get_ports sys_rst_n]

#==============================================================================
# LED Indicators (Reference: XC7K480T_MicroBlaze_Test)
# Only 3 LEDs used to match available pins
#==============================================================================

# LED[0] - Heartbeat
set_property PACKAGE_PIN M30 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[0]}]

# LED[1] - PLL Locked
set_property PACKAGE_PIN N30 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[1]}]

# LED[2] - Frame Activity
set_property PACKAGE_PIN P30 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[2]}]

#==============================================================================
# PCIe Constraints (Phase 2 - uncomment when adding XDMA)
#==============================================================================

# # PCIe reference clock (100MHz)
# set_property PACKAGE_PIN J8 [get_ports sys_clk_p]
# set_property PACKAGE_PIN J7 [get_ports sys_clk_n]
#
# # PCIe TX differential pairs
# set_property PACKAGE_PIN F2 [get_ports {pci_exp_txp[0]}]
# set_property PACKAGE_PIN H2 [get_ports {pci_exp_txp[1]}]
# set_property PACKAGE_PIN K2 [get_ports {pci_exp_txp[2]}]
# set_property PACKAGE_PIN M2 [get_ports {pci_exp_txp[3]}]
# set_property PACKAGE_PIN N4 [get_ports {pci_exp_txp[4]}]
# set_property PACKAGE_PIN P2 [get_ports {pci_exp_txp[5]}]
# set_property PACKAGE_PIN T2 [get_ports {pci_exp_txp[6]}]
# set_property PACKAGE_PIN U4 [get_ports {pci_exp_txp[7]}]

#==============================================================================
# DDR3 Constraints (Phase 3 - generated by MIG IP)
#==============================================================================
